import { createFileRoute } from "@tanstack/react-router";
import { PageHeader, Card, Badge, KPI } from "@/components/ui-bits";
import {
  MBP_WEEKS,
  MBP_OWNERS,
  getMbpState,
  updateMbpTasks,
  updateMbpMeetings,
  createTaskId,
  computeMbpKpis,
  filterTasks,
  statusTone,
  statusLabel,
  priorityTone,
  MBP_CHANGED_EVENT,
  type MbpTask,
  type MbpMeeting,
  type MbpFilters,
  type MbpWeekNumber,
  type MbpTaskStatus,
  type MbpPriority,
  type MbpOwner,
} from "@/lib/mbp";
import { CLEANING_CHANGED_EVENT } from "@/lib/cleaning";
import { DATA_CHANGED_EVENT } from "@/lib/data";
import { INSIGHTS_CHANGED_EVENT } from "@/lib/insights/store";
import { Calendar, CheckCircle2, Circle, Plus, Pencil } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { toast } from "sonner";

export const Route = createFileRoute("/app/mbp")({ component: MBP });

const EMPTY_TASK: Omit<MbpTask, "id"> = {
  week: 1,
  title: "",
  description: "",
  owner: "Demand Planner",
  area: "Demand Planner",
  dueDate: "2025-06-07",
  status: "pendiente",
  priority: "media",
};

function formatMeetingWhen(m: MbpMeeting): string {
  const d = new Date(m.date);
  const day = d.toLocaleDateString("es-AR", { weekday: "short", day: "2-digit", month: "2-digit" });
  return `${day} ${m.time}`;
}

function MBP() {
  const [tick, setTick] = useState(0);
  const [filters, setFilters] = useState<MbpFilters>({
    week: "all",
    area: "all",
    status: "all",
  });
  const [formOpen, setFormOpen] = useState(false);
  const [editing, setEditing] = useState<MbpTask | null>(null);
  const [draft, setDraft] = useState<Omit<MbpTask, "id">>(EMPTY_TASK);

  useEffect(() => {
    const refresh = () => setTick((t) => t + 1);
    window.addEventListener(INSIGHTS_CHANGED_EVENT, refresh);
    window.addEventListener(DATA_CHANGED_EVENT, refresh);
    window.addEventListener(CLEANING_CHANGED_EVENT, refresh);
    window.addEventListener(MBP_CHANGED_EVENT, refresh);
    return () => {
      window.removeEventListener(INSIGHTS_CHANGED_EVENT, refresh);
      window.removeEventListener(DATA_CHANGED_EVENT, refresh);
      window.removeEventListener(CLEANING_CHANGED_EVENT, refresh);
      window.removeEventListener(MBP_CHANGED_EVENT, refresh);
    };
  }, []);

  const state = useMemo(() => getMbpState(), [tick]);
  const { tasks, meetings, cycleMonth } = state;
  const kpis = useMemo(() => computeMbpKpis(tasks), [tasks]);

  const filtered = useMemo(() => filterTasks(tasks, filters), [tasks, filters]);

  const tasksByWeek = useMemo(() => {
    const map = new Map<MbpWeekNumber, MbpTask[]>();
    for (const w of MBP_WEEKS) map.set(w.week, []);
    for (const t of filtered) {
      const list = map.get(t.week) ?? [];
      list.push(t);
      map.set(t.week, list);
    }
    return map;
  }, [filtered]);

  const openCreate = () => {
    setEditing(null);
    setDraft({ ...EMPTY_TASK, dueDate: `${cycleMonth}-14` });
    setFormOpen(true);
  };

  const openEdit = (task: MbpTask) => {
    setEditing(task);
    setDraft({ ...task });
    setFormOpen(true);
  };

  const saveTask = () => {
    if (!draft.title.trim()) {
      toast.error("El título es obligatorio");
      return;
    }
    updateMbpTasks((manual) => {
      if (editing) {
        const next: MbpTask = {
          ...editing,
          ...draft,
          autoGenerated: false,
        };
        const without = manual.filter(
          (t) => t.id !== editing.id && t.autoKey !== editing.autoKey,
        );
        return [...without, next];
      }
      return [
        ...manual,
        { ...draft, id: createTaskId(), autoGenerated: false },
      ];
    });
    setFormOpen(false);
    setTick((t) => t + 1);
    toast.success(editing ? "Tarea actualizada" : "Tarea creada");
  };

  const persistTaskChange = (task: MbpTask, patch: Partial<MbpTask>) => {
    updateMbpTasks((manual) => {
      const updated: MbpTask = {
        ...task,
        ...patch,
        autoGenerated: false,
      };
      const without = manual.filter(
        (t) => t.id !== task.id && t.autoKey !== task.autoKey,
      );
      return [...without, updated];
    });
    setTick((t) => t + 1);
  };

  const toggleComplete = useCallback((task: MbpTask) => {
    const nextStatus: MbpTaskStatus =
      task.status === "completada" ? "pendiente" : "completada";
    persistTaskChange(task, { status: nextStatus });
  }, []);

  const setStatus = (task: MbpTask, status: MbpTaskStatus) => {
    persistTaskChange(task, { status });
  };

  const cycleLabel = useMemo(() => {
    const [y, m] = cycleMonth.split("-");
    const months = [
      "Enero",
      "Febrero",
      "Marzo",
      "Abril",
      "Mayo",
      "Junio",
      "Julio",
      "Agosto",
      "Septiembre",
      "Octubre",
      "Noviembre",
      "Diciembre",
    ];
    return `${months[Number(m) - 1] ?? m} ${y}`;
  }, [cycleMonth]);

  return (
    <div>
      <PageHeader
        title="Monthly Business Planning"
        subtitle={`Calendario MBP · ${cycleLabel}`}
        actions={
          <button
            type="button"
            onClick={openCreate}
            className="h-9 px-3 rounded-md bg-nestle-red text-white text-sm flex items-center gap-2"
          >
            <Plus className="size-4" />
            Nueva tarea
          </button>
        }
      />

      <div className="grid md:grid-cols-3 lg:grid-cols-5 gap-3 mb-6">
        <KPI label="% completadas" value={`${kpis.completedPct}%`} tone="good" />
        <KPI
          label="Atrasadas"
          value={String(kpis.overdueCount)}
          tone={kpis.overdueCount > 0 ? "bad" : "good"}
        />
        <KPI
          label="Insights pendientes"
          value={String(kpis.pendingInsights)}
          tone={kpis.pendingInsights > 0 ? "warn" : "good"}
        />
        <KPI
          label="Alertas críticas"
          value={String(kpis.criticalAlerts)}
          tone={kpis.criticalAlerts > 0 ? "bad" : "good"}
        />
        <KPI
          label="Forecast publicado"
          value={kpis.forecastPublished ? "Sí" : "No"}
          tone={kpis.forecastPublished ? "good" : "warn"}
        />
      </div>

      <Card className="mb-6">
        <div className="flex flex-wrap gap-2">
          <select
            value={filters.week === "all" ? "all" : String(filters.week)}
            onChange={(e) =>
              setFilters((f) => ({
                ...f,
                week:
                  e.target.value === "all"
                    ? "all"
                    : (Number(e.target.value) as MbpWeekNumber),
              }))
            }
            className="h-8 px-2 rounded border text-sm"
          >
            <option value="all">Todas las semanas</option>
            {MBP_WEEKS.map((w) => (
              <option key={w.week} value={w.week}>
                Semana {w.week}
              </option>
            ))}
          </select>
          <select
            value={filters.area}
            onChange={(e) =>
              setFilters((f) => ({
                ...f,
                area: e.target.value as MbpFilters["area"],
              }))
            }
            className="h-8 px-2 rounded border text-sm"
          >
            <option value="all">Todas las áreas</option>
            {MBP_OWNERS.map((a) => (
              <option key={a} value={a}>
                {a}
              </option>
            ))}
          </select>
          <select
            value={filters.status}
            onChange={(e) =>
              setFilters((f) => ({
                ...f,
                status: e.target.value as MbpFilters["status"],
              }))
            }
            className="h-8 px-2 rounded border text-sm"
          >
            <option value="all">Todos los estados</option>
            <option value="pendiente">Pendiente</option>
            <option value="en_progreso">En progreso</option>
            <option value="completada">Completada</option>
            <option value="atrasada">Atrasada</option>
            <option value="atrasadas">Solo atrasadas</option>
          </select>
        </div>
      </Card>

      <div className="grid lg:grid-cols-2 xl:grid-cols-4 gap-4 mb-6">
        {MBP_WEEKS.map((w) => {
          const weekTasks = tasksByWeek.get(w.week) ?? [];
          return (
            <Card key={w.week} title={`Semana ${w.week} · ${w.title}`}>
              <p className="text-xs text-muted-foreground mb-3">{w.summary}</p>
              <ul className="space-y-2">
                {weekTasks.length === 0 ? (
                  <li className="text-xs text-muted-foreground">
                    Sin tareas para este filtro.
                  </li>
                ) : (
                  weekTasks.map((t) => (
                    <li key={t.id} className="flex items-start gap-2 border-b border-border/50 pb-2 last:border-0">
                      <button
                        type="button"
                        onClick={() => toggleComplete(t)}
                        className="shrink-0 mt-0.5"
                      >
                        {t.status === "completada" ? (
                          <CheckCircle2 className="size-5 text-success" />
                        ) : (
                          <Circle className="size-5 text-muted-foreground" />
                        )}
                      </button>
                      <div className="flex-1 min-w-0">
                        <div
                          className={`text-sm ${t.status === "completada" ? "line-through text-muted-foreground" : ""}`}
                        >
                          {t.title}
                          {t.autoGenerated && (
                            <span className="text-[10px] text-muted-foreground ml-1">
                              (auto)
                            </span>
                          )}
                        </div>
                        <div className="flex flex-wrap gap-1 mt-1">
                          <Badge tone="info">{t.owner}</Badge>
                          <Badge tone={statusTone(t.status)}>
                            {statusLabel(t.status)}
                          </Badge>
                          <Badge tone={priorityTone(t.priority)}>
                            {t.priority}
                          </Badge>
                        </div>
                        <div className="flex gap-2 mt-1">
                          <button
                            type="button"
                            onClick={() => openEdit(t)}
                            className="text-[10px] text-nestle-red font-medium flex items-center gap-0.5"
                          >
                            <Pencil className="size-3" />
                            Editar
                          </button>
                          {t.status !== "completada" && (
                            <select
                              value={t.status === "atrasada" ? "pendiente" : t.status}
                              onChange={(e) =>
                                setStatus(t, e.target.value as MbpTaskStatus)
                              }
                              className="text-[10px] h-6 border rounded px-1"
                            >
                              <option value="pendiente">Pendiente</option>
                              <option value="en_progreso">En progreso</option>
                              <option value="completada">Completada</option>
                            </select>
                          )}
                        </div>
                      </div>
                    </li>
                  ))
                )}
              </ul>
            </Card>
          );
        })}
      </div>

      <Card title="Calendario de reuniones">
        <div className="space-y-2">
          {meetings.map((r) => (
            <div
              key={r.id}
              className="flex items-center gap-3 p-3 rounded-md border flex-wrap"
            >
              <div className="size-10 rounded-md bg-nestle-blue text-white grid place-items-center shrink-0">
                <Calendar className="size-5" />
              </div>
              <div className="flex-1 min-w-[200px]">
                <div className="font-medium text-sm">{r.title}</div>
                <div className="text-xs text-muted-foreground">
                  {formatMeetingWhen(r)} · {r.participants}
                </div>
                <div className="text-xs text-muted-foreground mt-0.5">
                  {r.objective}
                </div>
              </div>
              <Badge
                tone={
                  r.status === "realizada"
                    ? "good"
                    : r.status === "cancelada"
                      ? "bad"
                      : "info"
                }
              >
                {r.status}
              </Badge>
              <select
                value={r.status}
                onChange={(e) => {
                  updateMbpMeetings((list) =>
                    list.map((m) =>
                      m.id === r.id
                        ? {
                            ...m,
                            status: e.target.value as MbpMeeting["status"],
                          }
                        : m,
                    ),
                  );
                  setTick((t) => t + 1);
                }}
                className="h-7 text-xs border rounded px-1"
              >
                <option value="programada">Programada</option>
                <option value="realizada">Realizada</option>
                <option value="cancelada">Cancelada</option>
              </select>
            </div>
          ))}
        </div>
      </Card>

      {formOpen && (
        <div className="fixed inset-0 z-50 bg-black/40 grid place-items-center p-4">
          <div className="bg-card rounded-lg border shadow-lg w-full max-w-md p-4">
            <h3 className="font-medium mb-3">
              {editing ? "Editar tarea" : "Nueva tarea"}
            </h3>
            <div className="space-y-3 text-sm">
              <input
                className="w-full h-9 border rounded px-2"
                placeholder="Título"
                value={draft.title}
                onChange={(e) => setDraft((d) => ({ ...d, title: e.target.value }))}
              />
              <textarea
                className="w-full border rounded px-2 py-1 min-h-[60px]"
                placeholder="Descripción"
                value={draft.description}
                onChange={(e) =>
                  setDraft((d) => ({ ...d, description: e.target.value }))
                }
              />
              <div className="grid grid-cols-2 gap-2">
                <select
                  value={draft.week}
                  onChange={(e) =>
                    setDraft((d) => ({
                      ...d,
                      week: Number(e.target.value) as MbpWeekNumber,
                    }))
                  }
                  className="h-9 border rounded px-2"
                >
                  {MBP_WEEKS.map((w) => (
                    <option key={w.week} value={w.week}>
                      Semana {w.week}
                    </option>
                  ))}
                </select>
                <input
                  type="date"
                  value={draft.dueDate}
                  onChange={(e) =>
                    setDraft((d) => ({ ...d, dueDate: e.target.value }))
                  }
                  className="h-9 border rounded px-2"
                />
              </div>
              <div className="grid grid-cols-2 gap-2">
                <select
                  value={draft.owner}
                  onChange={(e) => {
                    const owner = e.target.value as MbpOwner;
                    setDraft((d) => ({ ...d, owner, area: owner }));
                  }}
                  className="h-9 border rounded px-2"
                >
                  {MBP_OWNERS.map((o) => (
                    <option key={o} value={o}>
                      {o}
                    </option>
                  ))}
                </select>
                <select
                  value={draft.priority}
                  onChange={(e) =>
                    setDraft((d) => ({
                      ...d,
                      priority: e.target.value as MbpPriority,
                    }))
                  }
                  className="h-9 border rounded px-2"
                >
                  <option value="baja">Baja</option>
                  <option value="media">Media</option>
                  <option value="alta">Alta</option>
                </select>
              </div>
              <select
                value={draft.status}
                onChange={(e) =>
                  setDraft((d) => ({
                    ...d,
                    status: e.target.value as MbpTaskStatus,
                  }))
                }
                className="h-9 border rounded px-2 w-full"
              >
                <option value="pendiente">Pendiente</option>
                <option value="en_progreso">En progreso</option>
                <option value="completada">Completada</option>
              </select>
            </div>
            <div className="flex justify-end gap-2 mt-4">
              <button
                type="button"
                onClick={() => setFormOpen(false)}
                className="h-9 px-3 rounded border text-sm"
              >
                Cancelar
              </button>
              <button
                type="button"
                onClick={saveTask}
                className="h-9 px-3 rounded bg-nestle-red text-white text-sm"
              >
                Guardar
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
