import { evaluateAlerts } from "@/lib/alerts";
import {
  buildCleaningSummary,
  buildDemandPointsForSku,
  detectOutliers,
  getSkuCleaning,
} from "@/lib/cleaning";
import { getInsights } from "@/lib/insights";
import { getConsensusStates } from "@/lib/insights/store";
import { DEMO_PRODUCTS } from "@/lib/mockData/catalog";
import { PRODUCTS } from "@/lib/mock-data";
import type { MbpOwner, MbpTask, MbpWeekNumber } from "./types";

function dueDateForWeek(week: MbpWeekNumber, cycleMonth: string): string {
  const day = { 1: 7, 2: 14, 3: 21, 4: 28 }[week];
  return `${cycleMonth}-${String(day).padStart(2, "0")}`;
}

function autoTask(
  partial: Omit<MbpTask, "id" | "autoGenerated"> & { autoKey: string },
): MbpTask {
  return {
    ...partial,
    id: `auto-${partial.autoKey}`,
    autoGenerated: true,
  };
}

const AREA_MAP: Record<string, MbpOwner> = {
  "Demand Planner": "Demand Planner",
  Marketing: "Marketing",
  Ventas: "Ventas",
  Finanzas: "Finanzas",
  Dirección: "Dirección",
};

function mapAlertOwner(owner: string): MbpOwner {
  return AREA_MAP[owner] ?? "Demand Planner";
}

const INSIGHT_AREA: Record<string, MbpOwner> = {
  Marketing: "Marketing",
  Ventas: "Ventas",
  Finanzas: "Finanzas",
};

export function buildAutoTasks(cycleMonth: string): MbpTask[] {
  const auto: MbpTask[] = [];

  let unclassifiedTotal = 0;
  for (const p of DEMO_PRODUCTS) {
    const stored = getSkuCleaning(p.code);
    const rows =
      stored?.rows ??
      detectOutliers(buildDemandPointsForSku(p.code), stored?.threshold ?? 3);
    unclassifiedTotal += buildCleaningSummary(rows).kpis.unclassifiedCount;
  }
  if (unclassifiedTotal > 0) {
    auto.push(
      autoTask({
        autoKey: "cleaning-unclassified",
        week: 1,
        title: "Clasificar outliers pendientes",
        description: `${unclassifiedTotal} outlier(s) sin evento asignado en limpieza.`,
        owner: "Demand Planner",
        area: "Demand Planner",
        dueDate: dueDateForWeek(1, cycleMonth),
        status: "pendiente",
        priority: "alta",
      }),
    );
  }

  const pendingByArea = new Map<MbpOwner, number>();
  for (const ins of getInsights()) {
    if (ins.estado_aprobacion !== "pendiente") continue;
    const area = INSIGHT_AREA[ins.area];
    if (!area) continue;
    pendingByArea.set(area, (pendingByArea.get(area) ?? 0) + 1);
  }
  for (const [area, count] of pendingByArea) {
    auto.push(
      autoTask({
        autoKey: `insight-pending-${area}`,
        week: 2,
        title: `Revisar insights pendientes (${area})`,
        description: `${count} insight(s) pendientes de aprobación.`,
        owner: area,
        area,
        dueDate: dueDateForWeek(2, cycleMonth),
        status: "pendiente",
        priority: "media",
      }),
    );
  }

  const critical = evaluateAlerts().alerts.filter(
    (a) => a.severity === "alta" && a.status === "open",
  );
  critical.slice(0, 5).forEach((alert, i) => {
    const owner = mapAlertOwner(alert.owner);
    auto.push(
      autoTask({
        autoKey: `alert-${alert.type}-${alert.skuCode}-${i}`,
        week: 3,
        title: `Resolver alerta: ${alert.sku}`,
        description: alert.message,
        owner,
        area: owner,
        dueDate: dueDateForWeek(3, cycleMonth),
        status: "pendiente",
        priority: "alta",
      }),
    );
  });

  const publishedCodes = new Set(
    getConsensusStates().filter((s) => s.published).map((s) => s.skuCode),
  );
  const unpublished = PRODUCTS.filter((p) => !publishedCodes.has(p.code));
  if (unpublished.length > 0) {
    auto.push(
      autoTask({
        autoKey: "forecast-publish",
        week: 4,
        title: "Publicar forecast consenso",
        description: `Pendiente publicación para ${unpublished.length} SKU(s).`,
        owner: "Demand Planner",
        area: "Demand Planner",
        dueDate: dueDateForWeek(4, cycleMonth),
        status: "pendiente",
        priority: "alta",
      }),
    );
  }

  return auto;
}

export function mergeAutoTasks(
  manualTasks: MbpTask[],
  cycleMonth: string,
): MbpTask[] {
  const manual = manualTasks.filter((t) => !t.autoGenerated);
  const auto = buildAutoTasks(cycleMonth);
  const suppressed = new Set(
    manual
      .filter((t) => t.autoKey && t.status === "completada")
      .map((t) => t.autoKey!),
  );
  const mergedAuto = auto.filter((a) => !suppressed.has(a.autoKey!));
  return [...manual, ...mergedAuto];
}
