import { mergeAutoTasks } from "./auto";
import { createDefaultMbpState } from "./seed";
import { withResolvedStatuses } from "./status";
import type { MbpMeeting, MbpPersistedState, MbpTask } from "./types";

const MBP_KEY = "nestle_mbp_state";

export const MBP_CHANGED_EVENT = "nestle-mbp-changed";

function emitChange(): void {
  if (typeof window !== "undefined") {
    window.dispatchEvent(new CustomEvent(MBP_CHANGED_EVENT));
  }
}

function loadRaw(): MbpPersistedState | null {
  if (typeof window === "undefined") return null;
  try {
    const raw = localStorage.getItem(MBP_KEY);
    if (!raw) return null;
    return JSON.parse(raw) as MbpPersistedState;
  } catch {
    return null;
  }
}

export function getMbpState(): MbpPersistedState {
  const raw = loadRaw();
  const base = raw ?? createDefaultMbpState();
  const tasks = withResolvedStatuses(
    mergeAutoTasks(base.tasks, base.cycleMonth),
  );
  return { ...base, tasks };
}

export function saveMbpState(state: MbpPersistedState): void {
  const toSave: MbpPersistedState = {
    ...state,
    tasks: state.tasks.filter((t) => !t.autoGenerated),
    updatedAt: new Date().toISOString(),
  };
  localStorage.setItem(MBP_KEY, JSON.stringify(toSave));
  emitChange();
}

export function updateMbpTasks(updater: (tasks: MbpTask[]) => MbpTask[]): void {
  const raw = loadRaw() ?? createDefaultMbpState();
  const manual = raw.tasks.filter((t) => !t.autoGenerated);
  const nextManual = updater(manual);
  saveMbpState({ ...raw, tasks: nextManual });
}

export function updateMbpMeetings(
  updater: (meetings: MbpMeeting[]) => MbpMeeting[],
): void {
  const state = getMbpState();
  saveMbpState({ ...state, meetings: updater(state.meetings) });
}

export function resetMbpToSeed(): MbpPersistedState {
  const fresh = createDefaultMbpState();
  saveMbpState(fresh);
  return getMbpState();
}

export function createTaskId(): string {
  return `mbp-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`;
}
