export const MBP_OWNERS = [
  "Demand Planner",
  "Marketing",
  "Ventas",
  "Finanzas",
  "Dirección",
] as const;

export type MbpOwner = (typeof MBP_OWNERS)[number];

export type MbpTaskStatus =
  | "pendiente"
  | "en_progreso"
  | "completada"
  | "atrasada";

export type MbpPriority = "baja" | "media" | "alta";

export type MbpWeekNumber = 1 | 2 | 3 | 4;

export interface MbpTask {
  id: string;
  week: MbpWeekNumber;
  title: string;
  description: string;
  owner: MbpOwner;
  area: MbpOwner;
  dueDate: string;
  status: MbpTaskStatus;
  priority: MbpPriority;
  autoGenerated?: boolean;
  autoKey?: string;
}

export type MeetingStatus = "programada" | "realizada" | "cancelada";

export interface MbpMeeting {
  id: string;
  type: string;
  title: string;
  date: string;
  time: string;
  participants: string;
  objective: string;
  status: MeetingStatus;
}

export interface MbpWeekDefinition {
  week: MbpWeekNumber;
  title: string;
  summary: string;
}

export interface MbpPersistedState {
  version: 1;
  cycleMonth: string;
  tasks: MbpTask[];
  meetings: MbpMeeting[];
  updatedAt: string;
}

export interface MbpKpis {
  completedPct: number;
  overdueCount: number;
  pendingInsights: number;
  criticalAlerts: number;
  forecastPublished: boolean;
  totalTasks: number;
}

export interface MbpFilters {
  week: "all" | MbpWeekNumber;
  area: "all" | MbpOwner;
  status: "all" | MbpTaskStatus | "atrasadas";
}
