/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppUsuariosRouteImport } from './routes/app.usuarios'
import { Route as AppMbpRouteImport } from './routes/app.mbp'
import { Route as AppLimpiezaRouteImport } from './routes/app.limpieza'
import { Route as AppInsightsRouteImport } from './routes/app.insights'
import { Route as AppForecastRouteImport } from './routes/app.forecast'
import { Route as AppFinanzasRouteImport } from './routes/app.finanzas'
import { Route as AppDireccionRouteImport } from './routes/app.direccion'
import { Route as AppDatosRouteImport } from './routes/app.datos'
import { Route as AppControlTowerRouteImport } from './routes/app.control-tower'
import { Route as AppConsensoRouteImport } from './routes/app.consenso'
import { Route as AppAiRouteImport } from './routes/app.ai'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsuariosRoute = AppUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AppRoute,
} as any)
const AppMbpRoute = AppMbpRouteImport.update({
  id: '/mbp',
  path: '/mbp',
  getParentRoute: () => AppRoute,
} as any)
const AppLimpiezaRoute = AppLimpiezaRouteImport.update({
  id: '/limpieza',
  path: '/limpieza',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppForecastRoute = AppForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanzasRoute = AppFinanzasRouteImport.update({
  id: '/finanzas',
  path: '/finanzas',
  getParentRoute: () => AppRoute,
} as any)
const AppDireccionRoute = AppDireccionRouteImport.update({
  id: '/direccion',
  path: '/direccion',
  getParentRoute: () => AppRoute,
} as any)
const AppDatosRoute = AppDatosRouteImport.update({
  id: '/datos',
  path: '/datos',
  getParentRoute: () => AppRoute,
} as any)
const AppControlTowerRoute = AppControlTowerRouteImport.update({
  id: '/control-tower',
  path: '/control-tower',
  getParentRoute: () => AppRoute,
} as any)
const AppConsensoRoute = AppConsensoRouteImport.update({
  id: '/consenso',
  path: '/consenso',
  getParentRoute: () => AppRoute,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/ai': typeof AppAiRoute
  '/app/consenso': typeof AppConsensoRoute
  '/app/control-tower': typeof AppControlTowerRoute
  '/app/datos': typeof AppDatosRoute
  '/app/direccion': typeof AppDireccionRoute
  '/app/finanzas': typeof AppFinanzasRoute
  '/app/forecast': typeof AppForecastRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/limpieza': typeof AppLimpiezaRoute
  '/app/mbp': typeof AppMbpRoute
  '/app/usuarios': typeof AppUsuariosRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/ai': typeof AppAiRoute
  '/app/consenso': typeof AppConsensoRoute
  '/app/control-tower': typeof AppControlTowerRoute
  '/app/datos': typeof AppDatosRoute
  '/app/direccion': typeof AppDireccionRoute
  '/app/finanzas': typeof AppFinanzasRoute
  '/app/forecast': typeof AppForecastRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/limpieza': typeof AppLimpiezaRoute
  '/app/mbp': typeof AppMbpRoute
  '/app/usuarios': typeof AppUsuariosRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/ai': typeof AppAiRoute
  '/app/consenso': typeof AppConsensoRoute
  '/app/control-tower': typeof AppControlTowerRoute
  '/app/datos': typeof AppDatosRoute
  '/app/direccion': typeof AppDireccionRoute
  '/app/finanzas': typeof AppFinanzasRoute
  '/app/forecast': typeof AppForecastRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/limpieza': typeof AppLimpiezaRoute
  '/app/mbp': typeof AppMbpRoute
  '/app/usuarios': typeof AppUsuariosRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/ai'
    | '/app/consenso'
    | '/app/control-tower'
    | '/app/datos'
    | '/app/direccion'
    | '/app/finanzas'
    | '/app/forecast'
    | '/app/insights'
    | '/app/limpieza'
    | '/app/mbp'
    | '/app/usuarios'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/ai'
    | '/app/consenso'
    | '/app/control-tower'
    | '/app/datos'
    | '/app/direccion'
    | '/app/finanzas'
    | '/app/forecast'
    | '/app/insights'
    | '/app/limpieza'
    | '/app/mbp'
    | '/app/usuarios'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/ai'
    | '/app/consenso'
    | '/app/control-tower'
    | '/app/datos'
    | '/app/direccion'
    | '/app/finanzas'
    | '/app/forecast'
    | '/app/insights'
    | '/app/limpieza'
    | '/app/mbp'
    | '/app/usuarios'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/usuarios': {
      id: '/app/usuarios'
      path: '/usuarios'
      fullPath: '/app/usuarios'
      preLoaderRoute: typeof AppUsuariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mbp': {
      id: '/app/mbp'
      path: '/mbp'
      fullPath: '/app/mbp'
      preLoaderRoute: typeof AppMbpRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/limpieza': {
      id: '/app/limpieza'
      path: '/limpieza'
      fullPath: '/app/limpieza'
      preLoaderRoute: typeof AppLimpiezaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/insights': {
      id: '/app/insights'
      path: '/insights'
      fullPath: '/app/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/forecast': {
      id: '/app/forecast'
      path: '/forecast'
      fullPath: '/app/forecast'
      preLoaderRoute: typeof AppForecastRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/finanzas': {
      id: '/app/finanzas'
      path: '/finanzas'
      fullPath: '/app/finanzas'
      preLoaderRoute: typeof AppFinanzasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/direccion': {
      id: '/app/direccion'
      path: '/direccion'
      fullPath: '/app/direccion'
      preLoaderRoute: typeof AppDireccionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/datos': {
      id: '/app/datos'
      path: '/datos'
      fullPath: '/app/datos'
      preLoaderRoute: typeof AppDatosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/control-tower': {
      id: '/app/control-tower'
      path: '/control-tower'
      fullPath: '/app/control-tower'
      preLoaderRoute: typeof AppControlTowerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/consenso': {
      id: '/app/consenso'
      path: '/consenso'
      fullPath: '/app/consenso'
      preLoaderRoute: typeof AppConsensoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ai': {
      id: '/app/ai'
      path: '/ai'
      fullPath: '/app/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAiRoute: typeof AppAiRoute
  AppConsensoRoute: typeof AppConsensoRoute
  AppControlTowerRoute: typeof AppControlTowerRoute
  AppDatosRoute: typeof AppDatosRoute
  AppDireccionRoute: typeof AppDireccionRoute
  AppFinanzasRoute: typeof AppFinanzasRoute
  AppForecastRoute: typeof AppForecastRoute
  AppInsightsRoute: typeof AppInsightsRoute
  AppLimpiezaRoute: typeof AppLimpiezaRoute
  AppMbpRoute: typeof AppMbpRoute
  AppUsuariosRoute: typeof AppUsuariosRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiRoute: AppAiRoute,
  AppConsensoRoute: AppConsensoRoute,
  AppControlTowerRoute: AppControlTowerRoute,
  AppDatosRoute: AppDatosRoute,
  AppDireccionRoute: AppDireccionRoute,
  AppFinanzasRoute: AppFinanzasRoute,
  AppForecastRoute: AppForecastRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppLimpiezaRoute: AppLimpiezaRoute,
  AppMbpRoute: AppMbpRoute,
  AppUsuariosRoute: AppUsuariosRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
